In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
url = "https://github.com/jamcro/shootGaze/blob/master/data/shootingNovice.csv"
#url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
c=pd.read_csv(url)
#gaze_df = pd.read_csv("~jc/Documents/GitHub/shootGaze/data/shootingNovice.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 114, saw 3

In [4]:
gaze_df.head(5)

,Subject,Intervention,Day,Trial,Timer,startTime,finishTime,Category,Position,Distance,Shot
0,1,0,1,1,7.05,7.685,8.722,B,2.0,5.0,0
1,1,0,1,1,7.05,8.790,9.419,A,1.0,5.0,0
2,1,0,1,1,7.05,9.470,13.006,B,2.0,5.0,1
3,1,0,1,1,7.05,13.074,15.947,C,3.0,7.0,0
4,1,0,1,1,7.05,15.981,17.834,D,4.0,9.0,0

In [6]:
c.head()

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA